### ISSUE TITLE
Is any help needed by the maintainers of this project?

### ISSUE THREAD

**Issue by ghost** [OWASP/Docker-Security#1]
I am currently working a lot with Docker and the security resources are pretty lacking. Is there anyway I can help?

**Comment by drwetter** [comment]
Hi Dan,

thanks. I'll dump the stuff I have (see talks @ the right hand side https://www.owasp.org/index.php/OWASP_Docker_Top_10) until Xmas and then it's time for discussions.

But if you happen to have comments upfront, let me know.

Cheers, Dirk
