### ISSUE TITLE
Typo "then" (instead of "ten") in cover.jpg (assets/cover.xcf) ?

### ISSUE THREAD

**Issue by hartwork** [OWASP/Docker-Security#16]
https://github.com/OWASP/Docker-Security/blob/master/cover.jpg reads "The Then Most Important Aspects". I read "then" as "back then" meaning distent past. Is it a typo of "ten" or was it supposed to mean "up to the date of publishing"? Looking at https://dict.leo.org/german-english/bisher I cannot find "then" as a candidate for translation.

**Comment by drwetter** [comment]
yes, I realized that actually rather late, i.e. this week as I gave a talk. @PauloASilva: where does that come from?

**Comment by hartwork** [comment]
Also found this just now: :smile: 

https://github.com/OWASP/Docker-Security/blob/d7eda996681aba411b84aa18943462e06ea5d015/book.json#L6

**Comment by PauloASilva** [comment]
It is definitely a typo. I'll fix it.

**Comment by PauloASilva** [comment]
Done, please check [PR#19].

Cheers,
Paulo A. Silva

[PR#19]: https://github.com/OWASP/Docker-Security/pull/19
