### ISSUE TITLE
Cover should mention "CC-BY-NC-SA 4.0 International", not just Creative Commons

### ISSUE THREAD

**Issue by hartwork** [OWASP/Docker-Security#18]
Hi!

There is a pile of Creative Commons licenses and the current logo used on the cover keeps the license very vague. I also didn't find any place in the document, where the license would be mentioned with more precision — maybe #4 is related? It would be nice to have "CC-BY-NC-SA 4.0 International" and maybe [its logo parts](https://creativecommons.org/licenses/by-nc-sa/4.0/), instead.

Thanks!

**Comment by drwetter** [comment]
Agree. This is something more for sooner then later.

I suggest the cover needs to be adjusted (cover.xcf) assets/first. Then if you have a peek at the application top 10:

![Screenshot_20191109_143048](https://user-images.githubusercontent.com/8036727/68529437-15919580-02ff-11ea-8414-f8014a5d9a7a.png)

the verbose description is on the TOC

**Comment by drwetter** [comment]
I pushed a new image (the WASP looks alos better now). Wasn't able though to include a link in the GIMP file for owasp.org and the license, that would be great too.

Second point to mention again: next page (TOC) needs a more thorough description of the license.

**Comment by drwetter** [comment]
closed via 56b3df6

**Comment by hartwork** [comment]
Thank you!
