### ISSUE TITLE
owasp/modsecurity vulnerabilites

### ISSUE THREAD

**Issue by githubcdr** [OWASP/Docker-Security#27]
Hi,

I noticed a lot of vulnerabilities in the owasp/modsecurity:3 Docker image. I didn't find a repo for the Docker image so posting here. (It feels a bit sour having to accept 2 critical and 106 high vulnerabilities if we want to implement WAF in our cluster..)

```
$ trivy i owasp/modsecurity:3

owasp/modsecurity:3 (debian 10.3)
=================================
Total: 569 (UNKNOWN: 2, LOW: 379, MEDIUM: 80, HIGH: 106, CRITICAL: 2)
```

The Docker image could use some attention, the source files are left in the container only wasting image size.

Could you address these vulnerabilities and create a repo for the source?

Cheers, cDR

**Comment by drwetter** [comment]
Hi there,

this is unfortunately the wrong place. 

Could you please address that here: https://github.com/coreruleset/coreruleset/ ?


Cheers, Dirk

**Comment by githubcdr** [comment]
Ok thanks for the quick response!

**Comment by drwetter** [comment]
sure. 

On the rhs @ https://owasp.org/www-project-modsecurity-core-rule-set/ there's the image probably you were referring to.
