### ISSUE TITLE
D06,D08,D09,D10 content lost

### ISSUE THREAD

**Issue by qitian100** [OWASP/Docker-Security#50]
D06,D08,D09,D10 content lost? why? someone delete or may I do something to recompile them?

**Comment by srcnuzn** [comment]
I assume, the content is not lost but was never provided (see for example [history](https://github.com/OWASP/Docker-Security/commits/main/D08%20-%20Container%20Image%20Integrity%20and%20Origin.md) for D08). Any insights/updates here?

**Comment by drwetter** [comment]
Yup. @srcnuzn is right. 

Personally I lacked time to work on this and at the moment I still do. That'll be changing hopefully by January.
